micronaut:
  application:
    name: demo
    instance:
      id: ${random.shortuuid}
  caches:
    discovery-client:
      enabled: false
  server:
    port: 8082
consul:
  client:
    registration:
      enabled: true
      ip-addr: ${IP:127.0.0.1}
      prefer-ip-address: true

    defaultZone: ${CONSUL_HOST:127.0.0.1}:${CONSUL_PORT:8500}

hazelcast.network.addresses: '[''192.168.0.105:5701'']'

endpoints:
  beans:
    enabled: true
    sensitive: false
  env:
    enabled: true
    sensitive: false
  loggers:
    write-sensitive: false
    enabled: true
    sensitive: false
  routes:
    enabled: true
    sensitive: false

